### ISSUE TITLE
Saving replay - adds extra frames at the end of the file

### ISSUE THREAD

**Issue by marlins-calendar** [exeldro/obs-replay-source#27]
[2021-02-24 11-07-56.txt](https://github.com/exeldro/obs-replay-source/files/6035797/2021-02-24.11-07-56.txt)
Hopefully I have attached the OBS studio log - apologies if it's not there - please let me know and I'll try again. (Bit new to all this!!)
Replay-source.dll is 1.6.7.0

I have a replay source set with a duration of 20000ms (20seconds).
When I 'load' the replay it loops round perfectly, showing 20seconds of video as expected.

When I save the file to .flv format, there is 5 seconds of 'extra' video added to the end of the file. The extra frames are just copies of the last good frame - in effect the replay video plays and then hangs for 5 seconds. 

It does this on different replay sources, and on a different machine running a different version of OBS.

Any assistance with this would be massively appreciated.
Thanks
Martin

I can't upload the original flv (not supported). I converted to an mp4 using handbrake but github says it's too big. If it would help, I can put the video up on onedrive or similar. 

PS Apologies for the user name as well!

**Comment by stepharvey** [comment]
Hey @marlins-calendar, I have the same issue on my side, cannot use these clips live on my show cause of that ending, so i had to do a workaround for now. Just in case this can help, im using the native buffer clips options from obs. I start the obs buffer save (works like shadowplay) and I bind the same key as my load clip in the replay pluggin for my obs save buffer replay. The difference is that it takes the whole streaming replay and not just the source, so its not as clean but at least i can show that during my show for my highlights right away instead of having broken clips.

**Comment by marlins-calendar** [comment]
Thanks for the reply - your level of expertise exceeds my level of understanding!!
My work around is currently based around using ffmpeg to remove the offending frames off the back of each clip. I have three cameras, and three replays. I'm looking to merge the replays into a single, replayable file - bit like the football on TV when they show the replays from different angles, one after the other.

Thanks again,
Martin

**Comment by stepharvey** [comment]
That's actually really really cool, and unfortunately not possible to do with my workaround since it only saves what's on-screen and not sources only.

**Comment by marlins-calendar** [comment]
I've upgraded replay-source to 1.6.8 and the 'extra' frames at the end appear to have been resolved - thank you very much.

I shall close this issue and will endeavour to keep everything up to date from now on!
